#!/bin/bash

if [ "$OPENAI_API_KEY" == "" ]; then
	echo "ERROR: OPENAI_API_KEY environment variable not set."
	exit 1
fi

if [ $# == 0 ]; then
	echo "USAGE: $0 <prompt>"
	exit 1
fi

P=${@//\"/\\\"}
PP=${P//\\\\\"/\\\\\\\"}

PAYLOAD="{\"model\":\"gpt-3.5-turbo\",\"messages\": [{\"role\":\"user\",\"content\":\"$PP\"}]}"

RESULT=$(curl -s https://api.openai.com/v1/chat/completions -H 'Content-Type: application/json' -H "Authorization: Bearer $OPENAI_API_KEY" -d "$PAYLOAD")

R=$(jq -r .choices[0].message.content <<< $RESULT)

if [ "$R" == "null" ]; then
	echo  "ERROR: Unexpected error returned."
	echo ""
	echo $RESULT
	echo ""
	exit 1
else
	echo -e "$R"
fi
